### ISSUE TITLE
Add blurb to Concept Exercises

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/rust#1185] opened 2021-03-02 15:48 UTC
Each Concept will have to define a _blurb_, which is a short description of the exercise.

In an earlier PR, a placeholder blurb has been added to the .meta/config.json file of each Concept Exercise. The placeholder blurbs should be replaced with an actual blurb for each Concept Exercise. Blurbs must be limited to 350 chars and will be truncated in some views.

For forked exercises, it might be useful to check how other tracks have defined their blurb.

The blurb will be displayed on a track's exercises page and on exercise tooltips. For example:

<img width="1194" alt="Screenshot 2021-03-02 at 13 25 38" src="https://user-images.githubusercontent.com/286476/109655154-da058500-7b5a-11eb-8346-bf733a72b3d0.png">
<img width="400" alt="Screenshot 2021-03-02 at 13 25 51" src="https://user-images.githubusercontent.com/286476/109655162-dd007580-7b5a-11eb-88f8-582532be9b84.png">

See the [Concept Exercise spec](https://github.com/exercism/docs/blob/main/anatomy/tracks/concept-exercises.md#file-metaconfigjson) for more information.

## Tracking

https://github.com/exercism/v3-launch/issues/23

**Comment by ayushmishra2005** [comment] 2021-05-13 04:04
@ErikSchierboom As I checked, blurb is already there with a short description https://github.com/exercism/rust/blob/main/concepts/structs/.meta/config.json#L2

Do you want to replace this with more detailed description(upto 350 characters)

**Comment by ErikSchierboom** [comment] 2021-05-14 08:32
@ayushmishra2005 No that's not needed. This issue was created for all tracks as a reminder to do this. It looks like Rust has already done this though:

```
find concepts -mindepth 3 -maxdepth 3 -name config.json -exec jq -r '.blurb' {} \;
"Boolean values store either `true` or `false` and are fundamental to computing."
"Option<T>: a T which may or may not be there"
"Basic enums: usage and creation with non-data-carrying variants"
"References enable borrowing, a core Rust feature."
"The `collect` method produces a collection from an iterator."
"Rust has two string types: `String` and `&str`."
"Integral numeric types and usage"
"`fold` is a flexible consuming iterator adaptor which produces a single value."
"Functions are fundamental units of code abstraction."
"Structs: fixed-size collections of heterogenous data"
"Rust has two string types: `String` and `&str`."
"String slices are Rust's immutable string type."
"Entry API for accessing and editing possibly-missing values in maps"
"Box stores values on the heap."
"The `char` data type stores a single unicode codepoint."
"Breaking tuples and structs into distinct named components"
"Non-integral numeric types and usage"
"Tuples are a lightweight way to group a fixed set of arbitrary types of data together."
```

That's looks great. So feel free to close this issue!

**Comment by ayushmishra2005** [comment] 2021-05-14 08:51
@ErikSchierboom I think you should be able to close the issue.

**Closed** 2021-05-14 09:07 UTC
Labels: help wanted, v3

**Comment by koushik-ms** [comment] 2021-09-13 13:51
there is the `concepts` folder with the definition of concepts and there is `exercise/concept` which contain Concept exercises. The goal of the issue is to ensure the concept exercises have blurbs and the csv-builder learning exercise seems missing the blurb (as noted [here](https://github.com/exercism/rust/issues/1303#issuecomment-913009925).

It is the only exercise having a placeholder blurb.
```
$ find exercises/concept -mindepth 3 -maxdepth 3 -name config.json -exec jq -r '.blurb' {} \;
Learn about numbers while working on an assembly line for cars.
TODO: add blurb for csv-builder exercise
Learn structs to store statistics for a health-monitoring system.
Learn tuples while writing convenience functions for a low-power embedded game
Learn about the basics of Rust by following a lasagna recipe.
Use `HashMap` and the entry API methods to write an anonymous letter.
Learn about the `Option` enum by creating a minimal role-playing game
Use some of `Vec`'s methods to evaluate Reverse Polish notation
Learn enums while building a logging utility.
Learn the `vec!` macro to build a short Fibonacci Sequence.
```
