### ISSUE TITLE
reverse_string exercise setup with deprecated graphemes feature

### ISSUE THREAD

**Issue by jackyzhen** [exercism/rust#672] opened 2018-10-17 08:45 UTC
The graphemes feature has been [deprecated since 1.3.0](https://users.rust-lang.org/t/where-did-str-graphemes-go/7817). Most suggestions point to the [unicode-segmentation crate](https://crates.io/crates/unicode-segmentation) instead.

**Comment by coriolinus** [comment] 2018-10-17 09:02
[exercise link](https://github.com/exercism/rust/tree/master/exercises/reverse-string)

At no point does this exercise use, encourage use of, or mention the deprecated `str.graphemes()` function. You're misunderstanding what the feature flag does. We declare a `grapheme` feature in `Cargo.toml`, and then have an extra test which may be optionally run by testing with that feature flag. This is described in the README. 

Closing as not a bug.

**Closed by coriolinus** 2018-10-17 09:02 UTC
