### ISSUE TITLE
Incorrect test case in Word Count exercise

### ISSUE THREAD

**Issue by sateeshkumarb** [exercism/rust#1265] opened 2021-05-15 11:31 UTC
The instructions of the wordcount exercise
https://github.com/exercism/rust/blob/main/exercises/practice/word-count/.docs/instructions.md
mention that words are separated by any form of whitespace, it states:

`The words can be separated by any form of whitespace (ie "\t", "\n", " ")`

However the test _cramped_lists_ (https://github.com/exercism/rust/blob/main/exercises/practice/word-count/tests/word-count.rs#L38) has this as test definition:

```
fn cramped_lists() {
    check_word_count("one,two,three", &[("one", 1), ("two", 1), ("three", 1)]);
}
```
Given that there are no whitespaces separating the three words the assertion verifying that phrases _one_, _two_  and _three_ have a frequency of 1 is not correct.

**Comment by coriolinus** [comment] 2021-05-15 18:19
Agree. The instructions should say that words are separated by non-word characters.

**Comment by kotp** [comment] 2021-05-15 22:54
I don't know that I agree with "should say that words are separated by non-word characters" exactly.  At least without declaring what that means.  The current wording also has a lot that it leaves out, ambiguity, a short example showing, but it only addresses 3 forms of white space, and doesn't identify the character clearly in quotes that appears like `" "`.

The current wording welcomes discussion from the student, encourages ambiguity confirmation from tests, and still leaves room for discussion about things such as those other kinds of "whitespace" characters that are not specifically addressed.

This might also be an issue addressed in https://github.com/exercism/problem-specifications.

There is also a missing period in "ie" so that should be corrected since it is given as source in this link that is given.

So there is room for many things here.  But the test, when passing, will have a frequency of 1 for each of those words, the test being directive, prescriptive in nature.

**Comment by kotp** [comment] 2021-05-15 22:54
@sateeshkumarb In summary of my comments above, are you interested in creating a pull request that shows how you believe this should be corrected?

**Comment by sateeshkumarb** [comment] 2021-05-16 10:32
@kotp I am of the opinion that it is better to keep the description as is (_i.e. the words can be separate from any form of whitespace_) and modify the test case. The test case can be changed so that the input is  `"one, two, three"` and the output validation would still hold. 

My understanding is intent of this test has been to let the learner learn about usage of HashMap, and get familiarity with operations on the type _&str_, both which won't be compromised if we stick to simpler requirement of words are separated by whitespace . Also the description can be improved a bit to say "one or more whitespace(s)". 

Also the example in the description is good enough and it need **not** be changed to include all forms of whitespaces, as its intent is provide a direction and not to provide exhaustive list of all possible input parameters.

Please let me know if you agree with above reasoning, I will create a PR accordingly.

**Comment by kotp** [comment] 2021-05-16 16:47
I think the whitespace addition in the test reaffirms the written words.  However, are the written words reaffirmed in other tests?  This test may reinforce that the whitespace is not needed, and provides an interpretation and confirmation of the "non-word" characters instead.

**Comment by sateeshkumarb** [comment] 2021-05-16 17:41
@kotp Of all the test _cramped_lists_ is the only one that has a non whitespace character as the separator. If we want to keep this test to enforce that whitespace is not needed (as a separator), then in which case shouldn't the test description be changed to indicate non-whitespace characters are also separators, the point  @coriolinus  has made.

**Comment by clstopher** [comment] 2021-05-23 00:27
Seeing as "word" is clearly defined in the section above (with 3 different definitions, but in this case as being one or more ascii letters), I don't agree that there is any ambiguity here to begin with. I'd even say that a string "one2three4five6seven" would have 7 distinct words, each with a single occurrence (one could argue that this isn't a phrase, but phrase isn't otherwise defined here ;) ).

**Comment by clstopher** [comment] 2021-05-23 00:35
Though I guess now I'll revise my above statement; "The words can be separated by any form of whitespace" *does* imply that there must be whitespace.  Maybe that could be "The words can be separated by any form of whitespace or punctuation"? Or change item 3 to be "Other than the apostrophe in a contraction all forms of punctuation can be treated as whitespace".

**Comment by coriolinus** [comment] 2021-05-23 05:43
My take is that the tests are authoritative as they constrain the expected behavior. Where the tests conflict with the documentation, the documentation should change.

**Comment by sateeshkumarb** [comment] 2021-05-23 12:42
I have created the PR https://github.com/exercism/rust/pull/1268 to update the exercise instructions. Please review.

**Closed** 2021-05-23 13:24 UTC
Labels: good first issue, help wanted
