### ISSUE TITLE
cargo running dotests by default causes error

### ISSUE THREAD

**Issue by dagda1** [exercism/rust#1600] opened 2022-11-27 19:11 UTC
When I first run the test with cargo `cargo 1.65.0 (4bc8f24d3 2022-10-20)`

I get this output after the successful running of the tests:

>    Doc-tests resistor-color
error[E0514]: found crate `int_enum` compiled by an incompatible version of rustc
 --> /Users/paulcowan/projects/exercism/rust/resistor-color/src/lib.rs:1:5
  |
1 | use int_enum::IntEnum;
  |     ^^^^^^^^
  |
  = help: please recompile that crate using this compiler (rustc 1.62.1) (consider running `cargo clean` first)
  = note: the following crate versions were found:d:
  
 On closer inspection, it appears to be something called `Doc-tests`

If I add this to the `Cargo.toml`, the `Doc-tests` (whatever they are) do not run and the error goes away:

```toml
[lib]
doctest = false
```

**Comment by petertseng** [comment] 2023-01-30 02:25
From searching for "compiled by an incompatible version of rustc", it looks like generally this is caused by having two instances of `rustc` installed at the same time.

**Comment by dagda1** [comment] 2023-01-30 04:41
@petertseng i found that on google as well but that was not the reason.   I only had one version.  So you can believe your own wrong assumption or try compiling against the latest version of cargo

**Comment by petertseng** [comment] 2023-01-30 06:03
That is a good idea! I see that the latest Cargo and rustc version are 1.67.0 so I installed those:

```
[pt@concept/resistor-color]$ cargo --version
cargo 1.67.0
[pt@concept/resistor-color]$ rustc --version
rustc 1.67.0 (fc594f156 2023-01-24)
```

Now I will run the tests.

```
[pt@concept/resistor-color]$ cargo test -- --include-ignored
   Compiling proc-macro2 v1.0.46
   Compiling unicode-ident v1.0.5
   Compiling quote v1.0.21
   Compiling syn v1.0.102
   Compiling serde v1.0.145
   Compiling thiserror v1.0.37
   Compiling once_cell v1.15.0
   Compiling toml v0.5.9
   Compiling thiserror-impl v1.0.37
   Compiling enum-iterator-derive v1.1.0
   Compiling enum-iterator v1.2.0
   Compiling proc-macro-crate v1.2.1
   Compiling int-enum-impl v0.5.0
   Compiling int-enum v0.5.0
   Compiling resistor-color v1.0.0 (/home/pt/src/exercism/rust/exercises/concept/resistor-color)
    Finished test [unoptimized + debuginfo] target(s) in 28.49s
     Running unittests src/lib.rs (target/debug/deps/resistor_color-665f3046ff950ed0)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/resistor-color.rs (target/debug/deps/resistor_color-93f77d07f408f253)

running 8 tests
test test_2 ... ok
test test_11_out_of_range ... ok
test test_8 ... ok
test test_6 ... ok
test test_orange ... ok
test test_white ... ok
test test_black ... ok
test test_all_colors ... ok

test result: ok. 8 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests resistor-color

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

Okay, so it looks like the problem is fixed with Cargo 1.67.0.

If we can figure out the cause of the issue, then we can put in a fix. Any information is valuable in helping figuring out the cause.

**Comment by petertseng** [comment] 2023-01-30 06:07
I also only have one version of rustc/cargo installed, so the cause of having two instances of rustc/cargo installed cannot possibly apply to me either.

**Comment by dagda1** [comment] 2023-01-30 06:31
If you look at my original comment, the fix for me was to add this to the `cargo.toml`

```ts
[lib]
doctest = false
```

Cargo must be checking the validity of the rust code in the README and failing.  Is the rust code valid?

I've posted about this on stackoverflow, and all anyone ever comes back with is that you must be running 2 versions of the compiler, which has been frustrating.

**Closed** 2023-09-09 22:31 UTC
