### ISSUE TITLE
gigasecond: Issues with chrono crate requirement

### ISSUE THREAD

**Issue by SaschaMann** [exercism/rust#1338] opened 2021-09-24 18:51 UTC
_These are from the bug report dump_

---

It is not possible to import the chrono crate

---

no matching package named `chrono` found

---

error: no matching package named `chrono` found
location searched: registry `crates-io`

Hello!

This exercise requires the external crate 'chrono'. However, when i try to submit the solution, the tests come back with error:
"building gigasecond: external crates not supported".

---

Running the test case on the browser and submitting the source code shows the following error

```
We received the following error when we ran your code:
WARNING: student did not upload Cargo.lock. This may cause build errors.
error: no matching package named `chrono` found
location searched: registry `crates-io`
required by package `gigasecond v2.0.0 (/mnt/exercism-iteration)`
As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without the offline flag.
```

---

Running the code in the editor before modifying it give the following

We received the following error when we ran your code:
WARNING: student did not upload Cargo.lock. This may cause build errors.
error: no matching package named `chrono` found
location searched: registry `crates-io`
required by package `gigasecond v2.0.0 (/mnt/exercism-iteration)`
As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without the offline flag.

---

cannot run tests

WARNING: student did not upload Cargo.lock. This may cause build errors.
error: no matching package named `chrono` found
location searched: registry `crates-io`
required by package `gigasecond v2.0.0 (/mnt/exercism-iteration)`
As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without the offline flag.

---

Hi,
This exercise uses the chrono package by default, but returns the following error when testing:

- error: no matching package named `chrono` found

---

Code works on Rust playground, however when clicking "Run Test" inside the online editor I get:
"We received the following error when we ran your code:

WARNING: student did not upload Cargo.lock. This may cause build errors.
error: no matching package named `chrono` found
location searched: registry `crates-io`"
required by package `gigasecond v2.0.0 (/mnt/exercism-iteration)`
As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without the offline flag."

---

crate provided by the exercise is not loaded (in the web editor) and throws error on running the tests

The crate's name is "chrono"

---

We received the following error when we ran your code:

WARNING: student did not upload Cargo.lock. This may cause build errors.
error: no matching package named `chrono` found
location searched: registry `crates-io`
required by package `gigasecond v2.0.0 (/mnt/exercism-iteration)`
As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without the offline flag.

I have no idea what to upload and how

---

We received the following error when we ran your code:
WARNING: student did not upload Cargo.lock. This may cause build errors.
error: no matching package named `chrono` found
location searched: registry `crates-io`
required by package `gigasecond v2.0.0 (/mnt/exercism-iteration)`
As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without the offline flag.

---

I've encountered the following error. I've reverted the exercise to start but it did not help

#####################
We received the following error when we ran your code:
WARNING: student did not upload Cargo.lock. This may cause build errors.
error: no matching package named `chrono` found
location searched: registry `crates-io`
required by package `gigasecond v2.0.0 (/mnt/exercism-iteration)`
As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without the offline flag.
#####################

---

error: no matching package named `chrono` found
(in offline-mode)

---

It seems that I can't use 'chrono' crate even though it's already included in the exercise. This is the error I get when I run tests:

WARNING: student did not upload Cargo.lock. This may cause build errors.
error: no matching package named `chrono` found
location searched: registry `crates-io`
required by package `gigasecond v2.0.0 (/mnt/exercism-iteration)`
As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without the offline flag.

---

In rust/exercises/gigasecond is not possible to compile, because of not available chrono crate. 

Output:
We received the following error when we ran your code:
WARNING: student did not upload Cargo.lock. This may cause build errors.
error: no matching package named `chrono` found
location searched: registry `crates-io`
required by package `gigasecond v2.0.0 (/mnt/exercism-iteration)`
As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without the offline flag.

---

Can't build on the online editor. The error is related to Caro.lock, I'm not know how to update it for online editor version.

---

WARNING: student did not upload Cargo.lock. This may cause build errors.
error: no matching package named `chrono` found
location searched: registry `crates-io`
required by package `gigasecond v2.0.0 (/mnt/exercism-iteration)`
As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without the offline flag.

---

_and a bunch more that all had the same info_

**Comment by petertseng** [comment] 2021-09-24 21:13
Huh, according to the docs apparently you can only mark an issue as a duplicate by specifically saying these words in a comment

Duplicate of https://github.com/exercism/rust/issues/1307

**Closed by petertseng** 2021-09-24 21:13 UTC
