### ISSUE TITLE
"external crates not supported" even though they're mentioned in exercise

### ISSUE THREAD

**Issue by drguildo** [exercism/rust#1325] opened 2021-09-15 18:42 UTC
I'm trying to do the Rust gigasecond exercise. Every single solution I've submitted has failed no matter which files I submit. The closest I can get is by submitting the src/lib.rs, Cargo.lock and Cargo.toml, but even then I get:

`building gigasecond: external crates not supported`

![image](https://user-images.githubusercontent.com/9282/133490476-9d5ac362-26cf-4858-9bcf-ed6a8febcf4b.png)

I don't understand why this is the case when the exercise itself explicitly mentions the chrono crate and tells me to use it for my solution (it's included in the default dependencies). I find it frustrating that I have a bunch of failed solutions, not because my solution is incorrect (all of the tests pass), but because the test automation server doesn't work properly.

**Comment by coriolinus** [comment] 2021-09-15 20:53
Duplicate of https://github.com/exercism/rust/issues/1307.

**Closed by coriolinus** 2021-09-15 20:53 UTC
