### ISSUE TITLE
Key feature doesn't render completely on desktop

### ISSUE THREAD

**Issue by SyedAhkam** [exercism/rust#1447] opened 2022-02-09 21:11 UTC
This might be a responsiveness issue.

## Expected

Display the text "Rust compiles by default to a single static executable, and cross-compilation is easy." including the "easy."

## Observation

The "easy." part is cut off.

![image](https://user-images.githubusercontent.com/52673095/153287089-e4b307e4-24b7-4565-85bf-6fe90f023b77.png)

## Note

- The complete text is indeed in the source. I have verified that.
- Resizing the window or opening the page on mobile displays the text correctly.

![image](https://user-images.githubusercontent.com/52673095/153287815-0af67bb8-f750-4db5-a12a-7baad5270cc1.png)

**Comment by coriolinus** [comment] 2022-02-10 01:18
Thanks for the report! I'm going to transfer this issue to the website repo.

**Comment by ErikSchierboom** [comment] 2022-02-10 07:47
Yep, this is a known issue. I'm closing this as a duplicate of https://github.com/exercism/exercism/issues/5883

**Closed by ErikSchierboom** 2022-02-10 07:47 UTC
