### ISSUE TITLE
Bug in "Gigasecond" submission

### ISSUE THREAD

**Issue by AthulMuralidhar** [exercism/rust#1332] opened 2021-09-19 14:30 UTC
This is my code for the exercise here: https://exercism.org/tracks/rust/exercises/gigasecond

```rust
extern crate chrono;
use chrono::{DateTime, Utc, Duration};

// Returns a Utc DateTime one billion seconds after start.
pub fn after(start: DateTime<Utc>) -> DateTime<Utc> {
    start + Duration::seconds(1000000000)
}
```

- I tried my solution locally and every test seems to pass, but on the editor in exercism, i get:
```bash
WARNING: student did not upload Cargo.lock. This may cause build errors.
error: no matching package named `chrono` found
location searched: registry `crates-io`
required by package `gigasecond v2.0.0 (/mnt/exercism-iteration)`
As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without the offline flag.
```

- i double checked with other submissions to this exercise and mine seems to be inline with them and i not sure why my submission is not working.

Any help would be welcome

**Comment by coriolinus** [comment] 2021-09-20 06:26
Duplicate of https://github.com/exercism/rust/issues/1307. External crates are not currently supported in the online editor.

**Closed by coriolinus** 2021-09-20 06:26 UTC
