### ISSUE TITLE
Rust chrono missing in online editor

### ISSUE THREAD

**Issue by ArcticSpaceFox** [exercism/rust#1314] opened 2021-09-06 15:58 UTC
Noticed in exercise https://exercism.org/tracks/rust/exercises/gigasecond

Error message : 
![image](https://user-images.githubusercontent.com/36639589/132242023-21cdeadd-07d8-46b3-bf09-59c0c6d5ce35.png)

**Comment by coriolinus** [comment] 2021-09-07 06:40
Duplicate of https://github.com/exercism/rust/issues/1307. 

Recommended workaround: solve the exercise offline, testing on your local machine, then "mark as complete" to progress.

**Closed by coriolinus** 2021-09-07 06:40 UTC
